image:
  app:
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/zilkroad-private/docs-client
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: aws-registry

port: 8080
targetPort: 8080

namespace: devnet

logPath: /app/logs

replicas: 1

resources:
  limits:
    cpu: 0.1
    memory: 128M
  requests:
    cpu: 0.1
    memory: 64M
