image:
  app:
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/zilkroad-private/docs-client
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: aws-registry

port: 3049
targetPort: 3049

namespace: devnet

logPath: /app/logs

replicas: 0

resources:
  limits:
    cpu: 0.1
    memory: 256M
  requests:
    cpu: 0.1
    memory: 256M
